title: Beven Nyamande
email: bevenfx@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   I love all things python...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: werkzeug
github_username: bevennyamande

# Build settings
sass:
  sass_dir: _sass
Kramdown:
  input: GFM
theme: minima


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
