site: Personal website for Beven Nyamande
url: beven.co.zw
title: 0xbeven - Blog Site
description: My blog where i post cybersecurity related activities and programming activites
googlewebfonts: Fira+Code:wght@400;500;700
twitter:
  username: 0xbeven
  card: summary
  creator: #yourusername
author:
  twitter: 0xbeven
  name: Beven Nyamande
  avatar:
  email: wasp00007@gmail.com
  url: beven.co.zw
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
